# Generated by Django 5.1.4 on 2025-01-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_his',
            name='img',
        ),
        migrations.RemoveField(
            model_name='pay_his',
            name='last_payment_date',
        ),
    ]
