# Generated by Django 5.1.4 on 2025-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0002_remove_pay_his_img_remove_pay_his_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscheme',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='product_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
