# Generated by Django 5.1.4 on 2025-01-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0005_alter_productscheme_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscheme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
